gDat <- read.delim("/home/eacton/R/Tutorials/gapminderDataFiveYear.txt")
str(gDat)
(snippet <- subset(gDat, country=="Canada"))
library(plyr)
(maxLeByCont <- ddply(gDat, ~continent, summarize, maxLifeExp= max(lifeExp)))
levels(maxLeByCont$continent)
(minGDPByCont <- ddply(gDat, ~continent, summarize, minGDP=min(gdpPercap)))
ddply(gDat, ~continent, summarize, nUniqCountries = length(unique(country)))
ddply(gDat, ~continent, function(x) return(c(nUniqCountries=length(unique(x$country)))))
ddply(gDat,~continent, summarize, minGDP=min(gdpPercap), maxGDP=max(gdpPercap), medianGDP=median(gdpPercap))
jCountry <- "France"
(jDat <- subset(gDat, country==jCountry))
library(lattice)
xyplot(lifeExp~year, jDat, type=c('p','r'))
jFit <- lm(lifeExp~year, jDat)
summary(jFit)
(yearMin <- min(gDat$year))
jFit <- lm(lifeExp~ I(year-yearMin), jDat)
summary(jFit)
class(jFit)
mode(jFit)
str(jFit)
names(jFit)
jFit$coefficients
coef(jFit)
jFun <- function(x) coef(lm(lifeExp~I(year-yearMin),x))
jFun(jDat)
jFun <- function(x) {estCoefs <- coef(lm(lifeExp~I(year-yearMin),x))
names(estCoefs) <- c("intercept","slope")
return(estCoefs)}
jFun(jDat)
jFun(subset(gDat, country=="Canada"))
jFun(subset(gDat, country=="Bolivia"))
jFun(subset(gDat, country=="Uruguay"))
jFun(subset(gDat, country=="China"))
jCoefs <- ddply(gDat, ~country, jFun)
str(jCoefs)
tail(jCoefs)
library(xtable)
set.seed(916)
foo <- jCoefs[sample(nrow(jCoefs), size=15),]
foo <- xtable(foo)
print(foo, type="html", include.rownames=FALSE)
print(foo, type="html", include.rownames=FALSE)
foo <- arrange(foo, intercept)
foo <- xtable(foo)
print(foo, type="html", include.rownames=FALSE)
foo <- arrange(foo, desc(intercept))
foo <- xtable(foo)
print(foo, type="html", include.rownames=FALSE)
jFunTwoArgs <- function(x, cvShift = min(gDat$year)) {
estCoefs <- coef(lm(lifeExp ~ I(year - cvShift), x))
names(estCoefs) <- c("intercept", "slope")
return(estCoefs)
}
jCoefsBest <- ddply(gDat, ~country+continent, jFunTwoArgs, cvShift=min(gDat$year))
jCoefsBest <- ddply(gDat, ~country+continent, jFunTwoArgs, cvShift=min(gDat$year))
jCoefsBest <- arrange(jCoefsBest, desc(intercept))
heads(jCoefsBest)
kDat <- readRDS("/home/eacton/R/stat540-2014-ACTON-ERICA/GSE4051_MINI.rds")
kMat <- as.matrix(kDat[c('crabHammer','eggBomb','poisonFang')])
str(kMat)
median(kMat[,1])
median(kMat[,'eggBomb'])
apply(kMat,2,median)
apply(kMat,2,quantile,probs=0.5)
apply(kMat,2,quantile,probs=c(0.25,0.75))
apply(kMat,1,min)
apply(kMat,1,which.min)
colnames(kMat)[apply(kMat,1,which.min)]
rowSums(kMat)
all.equal(rowSums(kMat), apply(kMat,1,sum))
colMeans(kMat)
all.equal(colMeans(kMat), apply(kMat,2aggregate(eggBomb~devStage,kDat,FUN=mean)
aggregate(eggBomb~gType*devStage,kDat,FUN=mean)
aggregate(eggBomb~devStage*gType,kDat,FUN=range)
,mean))

